# Generated by Django 5.0.2 on 2025-11-25 17:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('platform', models.CharField()),
                ('playoff_week_start', models.IntegerField()),
                ('division_mapping', models.JSONField()),
                ('league_settings', models.JSONField()),
                ('scoring_settings', models.JSONField()),
                ('roster_settings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TeamManagerAPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerESPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_player_id', models.CharField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSLEEPER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_player_id', models.CharField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.player')),
            ],
        ),
        migrations.CreateModel(
            name='Playoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playoff_teams', models.IntegerField()),
                ('season_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.seasonsettings')),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(null=True)),
                ('draft_type', models.CharField(null=True)),
                ('draft_settings', models.JSONField(null=True)),
                ('order', models.JSONField(null=True)),
                ('season_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.seasonsettings')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonSettingsESPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField()),
                ('season_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.seasonsettings')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonSettingsSLEEPER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField()),
                ('draft_id', models.CharField()),
                ('bracket_id', models.CharField()),
                ('season_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.seasonsettings')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing', models.IntegerField(null=True)),
                ('division', models.CharField(null=True)),
                ('division_standing', models.IntegerField(null=True)),
                ('seed', models.IntegerField(null=True)),
                ('draft_pick', models.IntegerField(null=True)),
                ('season_winner', models.BooleanField(default=False)),
                ('division_winner', models.BooleanField(default=False)),
                ('season_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.seasonsettings')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.teammanagerapp')),
            ],
        ),
        migrations.CreateModel(
            name='DraftPicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField()),
                ('pick_num', models.IntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.draft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.teammanagerapp')),
            ],
        ),
        migrations.CreateModel(
            name='TeamManagerESPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField()),
                ('team_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.teammanagerapp')),
            ],
        ),
        migrations.CreateModel(
            name='TeamManagerSLEEPER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField()),
                ('user_id', models.CharField()),
                ('team_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.teammanagerapp')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMatchups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('result', models.CharField()),
                ('weekly_winner', models.BooleanField(default=False)),
                ('playoff', models.BooleanField(default=False)),
                ('opp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='leaderboard.teammanagerapp')),
                ('season_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.seasonsettings')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.teammanagerapp')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('starter', models.BooleanField()),
                ('week', models.IntegerField()),
                ('season', models.IntegerField()),
                ('nfl_team', models.CharField(null=True)),
                ('injury_status', models.CharField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.player')),
                ('weeklymatchup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboard.weeklymatchups')),
            ],
        ),
    ]
