# Generated by Django 5.1.14 on 2025-11-26 01:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='draft_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='division',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='playerespn',
            name='external_player_id',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='playerpoints',
            name='injury_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerpoints',
            name='nfl_team',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playersleeper',
            name='external_player_id',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='platform',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='roster_settings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='seasonsettingsespn',
            name='league_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seasonsettingssleeper',
            name='bracket_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seasonsettingssleeper',
            name='draft_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seasonsettingssleeper',
            name='league_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammanagerespn',
            name='team_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammanagersleeper',
            name='team_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammanagersleeper',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklymatchups',
            name='result',
            field=models.CharField(max_length=2),
        ),
    ]
