# Generated by Django 5.1.14 on 2025-12-10 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionWeeklyMatchups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('result', models.CharField()),
                ('weekly_winner', models.BooleanField(default=False)),
                ('playoff', models.BooleanField(default=False)),
                ('opp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_opponent', to='leaderboard.teammanagerapp')),
                ('season_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.seasonsettings')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.teammanagerapp')),
            ],
        ),
        migrations.AddField(
            model_name='playerpoints',
            name='exhibtion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboard.exhibitionweeklymatchups'),
        ),
    ]
