# Generated by Django 5.1.14 on 2026-01-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_exhibitionweeklymatchups_playerpoints_exhibtion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammanagersleeper',
            name='user_id',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='roster_id',
            field=models.CharField(default=None, null=True),
        ),
    ]
