# Generated by Django 5.1.14 on 2026-01-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_remove_teammanagersleeper_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerespn',
            name='external_player_id',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='playersleeper',
            name='external_player_id',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='seasonsettings',
            name='season',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='teammanagerespn',
            name='team_id',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='teammanagersleeper',
            name='team_id',
            field=models.CharField(unique=True),
        ),
    ]
