# Generated by Django 5.1.14 on 2026-01-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_alter_playerespn_external_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionweeklymatchups',
            name='matchup_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerpoints',
            name='slot_position',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='weeklymatchups',
            name='matchup_id',
            field=models.IntegerField(null=True),
        ),
    ]
