# Generated by Django 5.1.14 on 2026-01-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_exhibitionweeklymatchups_matchup_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsettings',
            name='playoff_team_num',
            field=models.IntegerField(default=6),
        ),
    ]
